const notFound = (req, res) => {
  res.status(404).json({ error: `Route ${req.method} ${req.path} not found` });
};

export default notFound;

//? ESTE MIDDLEWARE SE ENCARGA DE MANEJAR LAS RUTAS QUE NO HAN SIDO DEFINIDAS EN LA APLICACIÓN. CUANDO UNA SOLICITUD LLEGA A UNA RUTA QUE NO EXISTE, ESTE MIDDLEWARE RESPONDE CON UN CÓDIGOS DE ESTADO 404 Y UN MENSAJE DE ERROR QUE INDICA QUE LA RUTA NO FUE ENCONTRADA. SE DEBE COLOCAR AL FINAL DE TODAS LAS RUTAS DEFINIDAS PARA ASEGURAR QUE SOLO SE EJECUTE CUANDO NINGUNA OTRA RUTA HAYA COINCIDIDO.